[positive_labels]
CLR = ["collar"]
TFR = ["tail fiber", "tail-fiber"]

[query]
additional_query = [
    "AND refseq[filter]",
    "AND phage[Title]",
    "NOT hypothetical[Title]",
    "NOT putative[Title]",
    "NOT putitive[Title]",
    "NOT probable[Title]",
    "NOT possible[Title]",
    "NOT unknown[Title]",
    "AND 50:1000000[SLEN]"
    ]

[positive_labels_placeholder]
MCP = ["major capsid", "major-capsid"]
MTL = ["major tail", "major-tail"]
m_CP = ["minor capsid", "minor-capsid"]
m_TL = ["minor tail", "minor-tail"]
PTL = ["portal"]
TSH = ["tail shaft", "tail-shaft", "sheath"]
TSP = ["tail spike", "tail-spike"]
HTJ = ["HTJ", "head-tail", "head tail"]
BPL = ["baseplate"]
