[labels]
HTJ = ["HTJ", "head-tail", "head tail"]
# BPL = ["baseplate"]
CLR = ["collar", "tail fiber", "tail-fiber"]
MCP = ["major capsid", "major-capsid"]
MTL = ["major tail", "major-tail"]
mCP = ["minor capsid", "minor-capsid"]
mTL = ["minor tail", "minor-tail"]
PTL = ["portal"]
TSH = ["tail shaft", "tail-shaft", "sheath"]
# TSP = ["tail spike", "tail-spike"]
# OTH = []
